# Generated by Django 5.0.7 on 2024-07-29 08:20

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0003_chatgroup_is_privet_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='is_privet',
            new_name='is_private',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
